from .Recombination import Recombination
from .SinglePointCrossover import SinglePointCrossover as GA_Recombination_SinglePointCrossover
from .TwoPointCrossover import TwoPointCrossover as GA_Recombination_TwoPointCrossover
from .CenterPointCrossover import CenterPointCrossover as GA_Recombination_CenterPointCrossover
from .UniformCrossover import UniformCrossover as GA_Recombination_UniformCrossover
