from FitnessFunction import FitnessFunction
from Gdt import Gdt as Fitness_Gdt
from RmsdGdtLddt import RmsdGdtLddt as Fitness_RmsdGdtLddt
from RmsdGdtEnergyScore import RmsdGdtEnergyScore as Fitness_RmsdGdtEnergyScore
from Lddt import Lddt as Fitness_Lddt
from NegativeRastrigin import NegativeRastrigin as Fitness_NegativeRastrigin
from SideChainPackingNegativeEnergyScore import SideChainPackingNegativeEnergyScore as Fitness_SideChainPackingNegativeEnergyScore
from NegativeCyclization import NegativeCyclization as Fitness_NegativeCyclization
